apiVersion: v1
kind: Namespace
metadata:
  name: databridge-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: databridge-frontend-deployment
  namespace: databridge-namespace
  labels:
    app: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: databridge-lite-frontend:latest
        ports:
        - containerPort: 80
